services:
  laravel-app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - laravel
    depends_on:
      - postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel
    depends_on:
      - laravel-app

  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel-db
      POSTGRES_USER: laravel-user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - '3377:5432'
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
